name: C:\Users\gilopez\AppData\Local\Continuum\Anaconda3\envs\py_3.4
dependencies:
- backports=1.0=py34_0
- backports_abc=0.4=py34_0
- boto=2.40.0=py34_0
- bz2file=0.98=py34_0
- cycler=0.10.0=py34_0
- cython=0.24=py34_0
- dateutil=2.4.1=py34_0
- decorator=4.0.9=py34_0
- entrypoints=0.2=py34_1
- gensim=0.12.4=np111py34_0
- get_terminal_size=1.0.0=py34_0
- ipykernel=4.3.1=py34_0
- ipython=4.2.0=py34_0
- ipython-notebook=4.0.4=py34_3
- ipython_genutils=0.1.0=py34_0
- jinja2=2.8=py34_1
- jpeg=8d=vc10_0
- jsonschema=2.5.1=py34_0
- jupyter_client=4.2.2=py34_0
- jupyter_core=4.1.0=py34_0
- libpng=1.6.17=vc10_1
- libtiff=4.0.6=vc10_1
- markupsafe=0.23=py34_2
- matplotlib=1.5.1=np111py34_0
- mistune=0.7.2=py34_0
- mkl=11.3.3=1
- nbconvert=4.2.0=py34_0
- nbformat=4.0.1=py34_0
- nltk=3.2.1=py34_0
- notebook=4.2.0=py34_0
- numpy=1.11.0=py34_1
- openssl=1.0.2h=vc10_0
- path.py=8.2.1=py34_0
- pickleshare=0.5=py34_0
- pip=8.1.1=py34_1
- pygments=2.1.3=py34_0
- pyparsing=2.1.4=py34_0
- pyqt=4.11.4=py34_6
- pyreadline=2.1=py34_0
- python=3.4.4=4
- python-dateutil=2.5.3=py34_0
- pytz=2016.4=py34_0
- pyzmq=15.2.0=py34_0
- qt=4.8.7=vc10_8
- requests=2.10.0=py34_0
- scikit-learn=0.17.1=np111py34_1
- scipy=0.17.1=np111py34_0
- setuptools=21.2.1=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_2
- six=1.10.0=py34_0
- smart_open=1.3.3=py34_0
- tk=8.5.18=vc10_0
- tornado=4.3=py34_1
- traitlets=4.2.1=py34_0
- vs2010_runtime=10.00.40219.1=1
- wheel=0.29.0=py34_0
- zlib=1.2.8=vc10_3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - smart-open==1.3.3

